/***************************************************************************//**
* File Name: cycfg_ble.c
* Version: 1.1
*
* Description:
* Bluetooth Low Energy (BLE) milddleware configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 291
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_ble.h"

#if (CY_BLE_CORE == CY_BLE_CORE_DUAL) || (CY_BLE_CORE == __CORTEX_M)

#include "cy_flash.h"
#include "cy_ble_common.h"

#if(CY_BLE_MODE_PROFILE)

/*******************************************************************************
*  BLE GAP CONFIGURATION
*******************************************************************************/

#if (CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_BROADCASTER)
    /* The timeout value of slow advertising with slow advertising interval parameters */
    static cy_stc_ble_gapp_adv_params_t cy_ble_gappAdvConfig[CY_BLE_GAP_PERIPHERAL_COUNT +
                                                             CY_BLE_GAP_BROADCASTER_COUNT] =
    {
        /* Peripheral configuration 0 */
        {
            .fastAdvIntervalMin = 0x0020u, 
            .fastAdvIntervalMax = 0x0030u, 
            .fastAdvTimeOut = 0x1Eu, 
            .slowAdvEnable = 0x00u, 
            .slowAdvIntervalMin = 0x0640u, 
            .slowAdvIntervalMax = 0x4000u, 
            .slowAdvTimeOut = 0x96u, 
        },
    };

    /* Advertising parameters */
    cy_stc_ble_gapp_disc_param_t cy_ble_discoveryParam[CY_BLE_GAP_PERIPHERAL_COUNT +
                                                       CY_BLE_GAP_BROADCASTER_COUNT] =
    {
        /* Peripheral configuration 0 */
        {
            .advIntvMin = 0x0020u, 
            .advIntvMax = 0x0030u, 
            .advType = CY_BLE_GAPP_CONNECTABLE_UNDIRECTED_ADV, 
            .ownAddrType = 0x00u, 
            .directAddrType = 0x00u, 
            .directAddr = {0x00u, 0x00u, 0x00u, 0x50u, 0xA0u, 0x00u}, 
            .advChannelMap = 0x07u, 
            .advFilterPolicy = 0x00u, 
        },
    };

    /* Advertising data */
    cy_stc_ble_gapp_disc_data_t cy_ble_discoveryData[CY_BLE_GAP_PERIPHERAL_COUNT +
                                                     CY_BLE_GAP_BROADCASTER_COUNT] =
    {
        /* Peripheral configuration 0 */
        {
            .advData = { 0x02u, 0x01u, 0x05u, 0x05u, 0x03u, 0x0Fu,
                0x18u, 0x0Au, 0x18u, 0x00u, 0x00u, 0x00u,
                0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
                0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
                0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
                0x00u }, 
            .advDataLen = 0x09u, 
        },
    };

    /* Scan response data */
    cy_stc_ble_gapp_scan_rsp_data_t cy_ble_scanRspData[CY_BLE_GAP_PERIPHERAL_COUNT +
                                                       CY_BLE_GAP_BROADCASTER_COUNT] =
    {
        /* Peripheral configuration 0 */
        {
            .scanRspData = { 0x0Eu, 0x09u, 0x42u, 0x61u, 0x74u, 0x74u,
                0x65u, 0x72u, 0x79u, 0x20u, 0x4Cu, 0x65u,
                0x76u, 0x65u, 0x6Cu, 0x00u, 0x00u, 0x00u,
                0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
                0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
                0x00u }, 
            .scanRspDataLen = 0x0Fu, 
        },
    };

    /* This array of type cy_stc_ble_gapp_disc_mode_info_t is present only when the
       BLE component is configured for Peripheral or Broadcaster GAP roles.
       It contains the Advertisement settings and also the Advertisement and
       Scan response data parameters entered in the customizer. This variable
       can be used by advanced users to change Advertisement settings,
       Advertisement or Scan response data in runtime.
    */
    cy_stc_ble_gapp_disc_mode_info_t cy_ble_discoveryModeInfo[CY_BLE_GAP_PERIPHERAL_COUNT +
                                                              CY_BLE_GAP_BROADCASTER_COUNT] =
    {
        /* Peripheral configuration 0 */
        {
            .discMode = 0x01u, 
            .advParam = &cy_ble_discoveryParam[0], 
            .advData = &cy_ble_discoveryData[0], 
            .scanRspData = &cy_ble_scanRspData[0], 
            .advTo = 0x1Eu, 
        },
    };
#endif /* (CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_BROADCASTER) */

#if (CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_OBSERVER)
    /* Initializes the cy_stc_ble_gapc_disc_info_t cy_ble_discoveryInfo structure */
    static cy_stc_ble_gapc_scan_params_t cy_ble_gapcScanConfig[CY_BLE_GAP_CENTRAL_COUNT +
                                                               CY_BLE_GAP_OBSERVER_COUNT] =
    {
        
    };

    /* This array of type cy_stc_ble_gapc_disc_info_t is present only when
       the BLE component is configured for Central or Observer GAP roles.
       It contains the Scan settings entered in the customizer.
       This variable can be used by advanced users to change Scan
       settings in runtime.
    */
    cy_stc_ble_gapc_disc_info_t cy_ble_discoveryInfo[CY_BLE_GAP_CENTRAL_COUNT +
                                                     CY_BLE_GAP_OBSERVER_COUNT] =
    {
        
    };
#endif /* (CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_OBSERVER)*/

#if (CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_CENTRAL)
    /** Default device security */
    cy_stc_ble_gap_auth_info_t cy_ble_authInfo[CY_BLE_AUTH_INFO_COUNT] =
    {
        /* Security configuration 0 */
        {
            .security = (CY_BLE_GAP_SEC_MODE_1 | CY_BLE_GAP_SEC_LEVEL_2 ), 
            .bonding = CY_BLE_GAP_BONDING_NONE, 
            .ekeySize = 0x10u, 
            .authErr = CY_BLE_GAP_AUTH_ERROR_NONE, 
            .pairingProperties = 0x00u, 
        },
    };
#endif /* (CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_CENTRAL) */


/*******************************************************************************
*  BLE GATT CONFIGURATION
*******************************************************************************/

#if (CY_BLE_GATT_ROLE_SERVER)
    static uint8_t cy_ble_attValues[CY_BLE_GATT_DB_ATT_VAL_COUNT] =
    {
        /* Device Name */
        (uint8_t)'B', (uint8_t)'a', (uint8_t)'t', (uint8_t)'t', (uint8_t)'e', (uint8_t)'r', (uint8_t)'y', (uint8_t)' ',
        (uint8_t)'L', (uint8_t)'e', (uint8_t)'v', (uint8_t)'e', (uint8_t)'l',

        /* Appearance */
        0x00u, 0x00u,

        /* Battery Level */
        0x00u,

        /* Characteristic Presentation Format */
        0x00u, 0x00u, 0x00u, 0x00u, 0x01u, 0x00u, 0x00u,

        /* Manufacturer Name String */
        (uint8_t)'C', (uint8_t)'y', (uint8_t)'p', (uint8_t)'r', (uint8_t)'e', (uint8_t)'s', (uint8_t)'s', (uint8_t)' ',
        (uint8_t)'S', (uint8_t)'e', (uint8_t)'m', (uint8_t)'i', (uint8_t)'c', (uint8_t)'o', (uint8_t)'n', (uint8_t)'d',
        (uint8_t)'u', (uint8_t)'c', (uint8_t)'t', (uint8_t)'o', (uint8_t)'r',

        /* Model Number String */
        (uint8_t)'P', (uint8_t)'S', (uint8_t)'o', (uint8_t)'C', (uint8_t)' ', (uint8_t)'6', (uint8_t)' ', (uint8_t)'M',
        (uint8_t)'C', (uint8_t)'U', (uint8_t)' ', (uint8_t)'w', (uint8_t)'i', (uint8_t)'t', (uint8_t)'h', (uint8_t)' ',
        (uint8_t)'B', (uint8_t)'L', (uint8_t)'E', (uint8_t)' ', (uint8_t)'B', (uint8_t)'a', (uint8_t)'t', (uint8_t)'t',
        (uint8_t)'e', (uint8_t)'r', (uint8_t)'y', (uint8_t)' ', (uint8_t)'L', (uint8_t)'e', (uint8_t)'v', (uint8_t)'e',
        (uint8_t)'l',

        /* Hardware Revision String */
        (uint8_t)'C', (uint8_t)'Y', (uint8_t)'8', (uint8_t)'C', (uint8_t)'K', (uint8_t)'I', (uint8_t)'T', (uint8_t)'-',
        (uint8_t)'0', (uint8_t)'6', (uint8_t)'2', (uint8_t)'-', (uint8_t)'B', (uint8_t)'L', (uint8_t)'E', (uint8_t)' ',
        (uint8_t)'P', (uint8_t)'S', (uint8_t)'o', (uint8_t)'C', (uint8_t)' ', (uint8_t)'6', (uint8_t)' ', (uint8_t)'B',
        (uint8_t)'L', (uint8_t)'E', (uint8_t)' ', (uint8_t)'P', (uint8_t)'i', (uint8_t)'o', (uint8_t)'n', (uint8_t)'e',
        (uint8_t)'e', (uint8_t)'r', (uint8_t)' ', (uint8_t)'K', (uint8_t)'i', (uint8_t)'t',

        /* Firmware Revision String */
        (uint8_t)'V', (uint8_t)'1', (uint8_t)'.', (uint8_t)'0',
    };

    #if (CY_BLE_GATT_DB_CCCD_COUNT != 0u)
    static uint8_t cy_ble_attValuesCCCD[CY_BLE_GATT_DB_CCCD_COUNT];
    #endif /* CY_BLE_GATT_DB_CCCD_COUNT != 0u */

    #if (CY_BLE_ATT_UUID_128_COUNT != 0u)
    static const uint8_t cy_ble_attUuid128[CY_BLE_ATT_UUID_128_COUNT][16u] =
    {
        
    };
    #endif /* defined(CY_BLE_ATT_UUID_128_COUNT) */

    static cy_stc_ble_gatts_att_gen_val_len_t cy_ble_attValuesLen[CY_BLE_GATT_DB_ATT_VAL_LEN_COUNT] =
    {
        { 0x000Du, (void *)&cy_ble_attValues[0] }, /* Device Name */
        { 0x0002u, (void *)&cy_ble_attValues[13] }, /* Appearance */
        { 0x0001u, (void *)&cy_ble_attValues[15] }, /* Battery Level */
        { 0x0007u, (void *)&cy_ble_attValues[16] }, /* Characteristic Presentation Format */
        { 0x0002u, (void *)&cy_ble_attValuesCCCD[0] }, /* Client Characteristic Configuration */
        { 0x0015u, (void *)&cy_ble_attValues[23] }, /* Manufacturer Name String */
        { 0x0021u, (void *)&cy_ble_attValues[44] }, /* Model Number String */
        { 0x0026u, (void *)&cy_ble_attValues[77] }, /* Hardware Revision String */
        { 0x0004u, (void *)&cy_ble_attValues[115] }, /* Firmware Revision String */
    };

    /* GATT Data Base */
    static const cy_stc_ble_gatts_db_t cy_ble_gattDB[CY_BLE_GATT_DB_INDEX_COUNT] =
    {
        { 0x0001u, 0x2800u /* Primary service                     */, 0x00000001u /*        */, 0x0005u, {{0x1800u, NULL}}                           },
        { 0x0002u, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x0003u, {{0x2A00u, NULL}}                           },
        { 0x0003u, 0x2A00u /* Device Name                         */, 0x01020001u /* rd     */, 0x0003u, {{0x000Du, (void *)&cy_ble_attValuesLen[0]}} },
        { 0x0004u, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x0005u, {{0x2A01u, NULL}}                           },
        { 0x0005u, 0x2A01u /* Appearance                          */, 0x01020001u /* rd     */, 0x0005u, {{0x0002u, (void *)&cy_ble_attValuesLen[1]}} },
        { 0x0006u, 0x2800u /* Primary service                     */, 0x00000001u /*        */, 0x0006u, {{0x1801u, NULL}}                           },
        { 0x0007u, 0x2800u /* Primary service                     */, 0x00000001u /*        */, 0x000Bu, {{0x180Fu, NULL}}                           },
        { 0x0008u, 0x2803u /* Characteristic                      */, 0x00120001u /* rd,ntf */, 0x000Bu, {{0x2A19u, NULL}}                           },
        { 0x0009u, 0x2A19u /* Battery Level                       */, 0x01120003u /* rd,ntf */, 0x000Bu, {{0x0001u, (void *)&cy_ble_attValuesLen[2]}} },
        { 0x000Au, 0x2904u /* Characteristic Presentation Format  */, 0x01020003u /* rd     */, 0x000Au, {{0x0007u, (void *)&cy_ble_attValuesLen[3]}} },
        { 0x000Bu, 0x2902u /* Client Characteristic Configuration */, 0x030A0303u /* rd,wr  */, 0x000Bu, {{0x0002u, (void *)&cy_ble_attValuesLen[4]}} },
        { 0x000Cu, 0x2800u /* Primary service                     */, 0x00000001u /*        */, 0x0014u, {{0x180Au, NULL}}                           },
        { 0x000Du, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x000Eu, {{0x2A29u, NULL}}                           },
        { 0x000Eu, 0x2A29u /* Manufacturer Name String            */, 0x01020001u /* rd     */, 0x000Eu, {{0x0015u, (void *)&cy_ble_attValuesLen[5]}} },
        { 0x000Fu, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x0010u, {{0x2A24u, NULL}}                           },
        { 0x0010u, 0x2A24u /* Model Number String                 */, 0x01020001u /* rd     */, 0x0010u, {{0x0021u, (void *)&cy_ble_attValuesLen[6]}} },
        { 0x0011u, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x0012u, {{0x2A27u, NULL}}                           },
        { 0x0012u, 0x2A27u /* Hardware Revision String            */, 0x01020001u /* rd     */, 0x0012u, {{0x0026u, (void *)&cy_ble_attValuesLen[7]}} },
        { 0x0013u, 0x2803u /* Characteristic                      */, 0x00020001u /* rd     */, 0x0014u, {{0x2A26u, NULL}}                           },
        { 0x0014u, 0x2A26u /* Firmware Revision String            */, 0x01020001u /* rd     */, 0x0014u, {{0x0004u, (void *)&cy_ble_attValuesLen[8]}} },
    };
#endif /* (CY_BLE_GATT_ROLE_SERVER) */


/*******************************************************************************
*  BLE PARAMETERS CONFIGURATIONS
*******************************************************************************/

static const cy_stc_ble_params_t cy_ble_params = {
    /** Silicon Device Address Enabled */
    .siliconDeviceAddressEn = 0x01u,

    /** Using external buffer for Prepare Write Request */
    .gattPrepareWriteExtBuffEn = CY_BLE_GATT_EN_EXT_PREP_WRITE_BUFF,

    /** The parameter to enable the configuration of the L2CAP logical channels. */
    .l2capEn = CY_BLE_L2CAP_ENABLE,

    /** The Bonding Requirement */
    .isBondingReq = CY_BLE_BONDING_REQUIREMENT,

    /** BLESS Power reflecting power level values supported by BLESS radio
     * (for advertising channel) */
    .txPowerLevelAdv = CY_BLE_LL_PWR_LVL_0_DBM,

    /** BLESS Power reflecting power level values supported by BLESS radio
     * (for connection channel) */
    .txPowerLevelConn = CY_BLE_LL_PWR_LVL_0_DBM,

    /** IO capability */
    .securityIoCapability = CY_BLE_GAP_IOCAP_NOINPUT_NOOUTPUT,

    /** L2CAP MTU Size */
    .l2capMtuSize = CY_BLE_L2CAP_MTU,

    /** L2CAP MPS Size */
    .l2capMps = CY_BLE_L2CAP_MPS,

    /** The number of L2CAP Logical channels */
    .l2capChanCount = CY_BLE_L2CAP_LOGICAL_CHANNEL_COUNT,

    /** Number of L2CAP PSMs */
    .l2capPsmCount = CY_BLE_L2CAP_PSM_COUNT,

    /** Size of prepareWriteQueue buffer */
    .gattPrepareWriteQueueSize = CY_BLE_GATT_MAX_PREPARE_BUFF_COUNT,

    /** Length of attribute value */
    .totalAttrValueLength = CY_BLE_GATT_PREPARE_LENGTH_ALIGN,

    /** The GATT Maximum attribute length */
    .gattAttrMaxLen = CY_BLE_GATT_DB_MAX_VALUE_LEN,

    /** Index count for GATT DB */
    .gattDbIndexCount  = CY_BLE_GATT_DB_INDEX_COUNT,

    /** GATT MTU Size */
    .mtuSize = CY_BLE_GATT_MTU,

    /** The GAP Role */
    .gapRole = CY_BLE_GAP_ROLE,

    /** The number of GAP Peripheral configurations */
    .gappConfCount = CY_BLE_GAP_PERIPHERAL_COUNT + CY_BLE_GAP_BROADCASTER_COUNT,

    /** The number of GAP Central configurations */
    .gapcConfCount = CY_BLE_GAP_CENTRAL_COUNT + CY_BLE_GAP_OBSERVER_COUNT,

    /** GATT Role */
    .gattRole = CY_BLE_GATT_ROLE,

    /** The number of BLE connections (client) */
    .maxClientCount = CY_BLE_GATTC_COUNT,
};


/*******************************************************************************
 *  Flash storage
 *******************************************************************************/
#if(CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL)
#if (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES)
    /* Allocate flash storage for bond data */
    CY_SECTION(".cy_em_eeprom") CY_ALIGN(CY_FLASH_SIZEOF_ROW)
    static const uint8_t stackFlashStorage[CY_BLE_STACK_FLASH_SIZE] = { 0u };

    /* Allocate flash storage for CCCD data */
    #if (CY_BLE_GATT_DB_CCCD_COUNT != 0u)
    CY_SECTION(".cy_em_eeprom") CY_ALIGN(CY_FLASH_SIZEOF_ROW)
    static const uint8_t cccdFlashStorage[CY_BLE_MAX_BONDED_DEVICES + CY_BLE_CONN_COUNT]
                                         [CY_BLE_GATT_DB_CCCD_COUNT + CY_BLE_CCCD_CRC_BYTE] = { 0u };
    #endif /* (CY_BLE_GATT_DB_CCCD_COUNT != 0u) */
#endif /* (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES) */

#if (CY_BLE_GATT_DB_CCCD_COUNT != 0u) && (CY_BLE_MODE_PROFILE)
    /* RAM storage for CCCD data */
    static uint8_t cccdRamStorage[CY_BLE_CONN_COUNT][CY_BLE_GATT_DB_CCCD_COUNT + CY_BLE_CCCD_CRC_BYTE];
#endif /* (CY_BLE_GATT_DB_CCCD_COUNT != 0u) && (CY_BLE_MODE_PROFILE)  */

    static const cy_stc_ble_flash_storage_t cy_ble_flashStorage =
    {
        /* Bond data storage */
        #if (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES)
        .stackFlashPtr   = (uint8_t *)stackFlashStorage,
        .stackFlashSize  = CY_BLE_STACK_FLASH_SIZE,
        #endif /* (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES) */

        /* CCCD Flash storage */
        #if (CY_BLE_GATT_DB_CCCD_COUNT != 0u) && (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES)
        .cccdFlashPtr    = (uint8_t *)cccdFlashStorage,
        #endif /* (CY_BLE_BONDING_REQUIREMENT == CY_BLE_BONDING_YES) */

        /* CCCD RAM storage */
        #if (CY_BLE_GATT_DB_CCCD_COUNT != 0u)
        .cccdRamPtr      = (uint8_t *)cccdRamStorage,
        .cccdCount       = CY_BLE_GATT_DB_CCCD_COUNT,
        #endif /* (CY_BLE_GATT_DB_CCCD_COUNT != 0u) */
    };
#endif /* (CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL) */


/*******************************************************************************
 *  Internal structures for registration and discovery services
 *******************************************************************************/
 
#if (CY_BLE_GATT_ROLE_SERVER || CY_BLE_GATT_ROLE_CLIENT)
    /* Array of registered service callbacks */
    cy_ble_event_handle_t serviceEventHandler[CY_BLE_MAX_SRVI];

    /* Structure to store registered services callbacks */
    cy_stc_ble_event_handler_t cy_ble_eventHandler =
    {
        .serviceEventHandler = serviceEventHandler,
        .maxServCount        = CY_BLE_MAX_SRVI
    };

    /* Array of discovery services */
    #if (CY_BLE_GATT_ROLE_CLIENT)
    cy_stc_ble_discovery_t cy_ble_discovery[CY_BLE_GATTC_COUNT];
    cy_stc_ble_disc_srvc_info_t cy_ble_serverInfo[CY_BLE_GATTC_COUNT][CY_BLE_SRVI_COUNT];
    #endif /* (CY_BLE_GATT_ROLE_SERVER) */

    cy_stc_ble_context_t cy_ble_contex =
    {
        /* Service callbacks */
        .eventHandlerPool = &cy_ble_eventHandler,

    #if (CY_BLE_GATT_ROLE_CLIENT)
        .discovery       = cy_ble_discovery,
        .serverInfo      = (cy_stc_ble_disc_srvc_info_t *) &cy_ble_serverInfo,
        .discServiCount  = CY_BLE_SRVI_COUNT,
    #endif /* (CY_BLE_GATT_ROLE_SERVER) */
    };
#endif /* (CY_BLE_GATT_ROLE_SERVER || CY_BLE_GATT_ROLE_CLIENT) */

#endif /* (CY_BLE_MODE_PROFILE) */


/*******************************************************************************
 *  BLE STACK configuration / RAM buffer allocation
 *******************************************************************************/

 /* Allocate RAM memory for the stack. This buffer can be reused by the application when
 * the BLE middleware is stopped. For the export mode, the buffer is allocated in a heap.
 */
#if (!CY_BLE_SHARING_MODE_EXPORT)
    CY_ALIGN(sizeof(uint32_t)) CY_NOINIT uint8_t cy_ble_stackMemoryRam[CY_BLE_STACK_RAM_SIZE];
#endif  /* !CY_BLE_SHARING_MODE_EXPORT */

/** BLE Stack parameters */
cy_stc_ble_stack_params_t stackParam =
{
    /** Memory Heap pointer */
    #if (!CY_BLE_SHARING_MODE_EXPORT)
    .memoryHeapPtr =  cy_ble_stackMemoryRam,
    #endif  /* CY_BLE_SHARING_MODE_EXPORT */

    /** Memory heap pointer size */
    #if (CY_BLE_MODE_PROFILE)
        .totalHeapSz =  CY_BLE_STACK_RAM_SIZE - CY_BLE_GATT_PREPARE_WRITE_BUFF_LEN,
    #else
        .totalHeapSz =  CY_BLE_STACK_RAM_SIZE,
    #endif /* (CY_BLE_MODE_PROFILE) */

    /** Configuration for the L2CAP buffer for data transmission */
    .l2capBufferPerConn =  CY_BLE_L2CAP_Q_DEPTH_PER_CONN,

    /** Max Tx payload size. */
    .dleMaxTxCapability =  CY_BLE_LL_MAX_TX_PAYLOAD_SIZE,

    /** Max Rx payload size. */
    .dleMaxRxCapability =  CY_BLE_LL_MAX_RX_PAYLOAD_SIZE,

    /** The feature set mask used to control usage of specified feature in the BLE stack */
    .featureMask = (CY_BLE_DLE_FEATURE | CY_BLE_LL_PRIVACY_FEATURE |
                    CY_BLE_SECURE_CONN_FEATURE | CY_BLE_PHY_UPDATE_FEATURE |
                    CY_BLE_STORE_BONDLIST_FEATURE | CY_BLE_STORE_RESOLVING_LIST_FEATURE |
                    CY_BLE_STORE_WHITELIST_FEATURE | CY_BLE_TX_POWER_CALIBRATION_FEATURE),

    /** The maximum number of devices that can be added to the resolve list */
    .maxResolvableDevListSize = CY_BLE_MAX_RESOLVABLE_DEVICES,

    /** The maximum number of devices that can be added to the white list */
    .maxBondedDevListSize = CY_BLE_MAX_BONDED_DEVICES,

    /** The maximum number of bonded devices to be supported by this device */
    .maxWhiteListSize = CY_BLE_MAX_WHITE_LIST_SIZE,

    /** Maximum number of BLE connections */
    .maxConnCount = CY_BLE_CONN_COUNT,

    /** Tx 5dbm mode enable */
    .tx5dbmModeEn = CY_BLE_ENABLE_TX_5DBM,

    /** Package type */
    #if defined(CY_GPIO_PIN_COUNT)
    .packageType = CY_GPIO_PACKAGE_TYPE | (CY_GPIO_PIN_COUNT << CY_BLE_PACKAGE_PIN_NUM_OFFSET),
    #else
    .packageType = CY_GPIO_PACKAGE_TYPE,
    #endif /* defined(CY_GPIO_PIN_COUNT) */    
};


/*******************************************************************************
 *  Initialize the configuration structure for BLE
 *******************************************************************************/

/** BD Address of device */
cy_stc_ble_gap_bd_addr_t cy_ble_deviceAddress =
{
    {0x00u, 0x00u, 0x00u, 0x50u, 0xA0u, 0x00u}, 0x0u
};

/** HW configuration */
cy_stc_ble_hw_config_t cy_ble_hwConfig = { NULL };

const cy_stc_ble_config_t cy_ble_config =
{
#if (CY_BLE_MODE_PROFILE)
    /** Initialize the GAPP structures */
    #if(CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_BROADCASTER)
    .discoveryModeInfo = cy_ble_discoveryModeInfo,
    .gappAdvParams = cy_ble_gappAdvConfig,
    #endif /* CY_BLE_GAP_ROLE_PERIPHERAL || CY_BLE_GAP_ROLE_BROADCASTER */

    /** Initialize the GAPC structures */
    #if(CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_OBSERVER)
    .discoveryInfo = cy_ble_discoveryInfo,
    .gapcScanParams = cy_ble_gapcScanConfig,
    #endif /* CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_OBSERVER */

    /** Initialize the GATT structures */
    #if(CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL)
    .flashStorage = &cy_ble_flashStorage,
    #endif /* CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL) */
    
    #if(CY_BLE_GATT_ROLE_SERVER)
    #if(CY_BLE_GATT_DB_CCCD_COUNT != 0u)
    .attValuesCCCD = cy_ble_attValuesCCCD,
    #endif /* (CY_BLE_GATT_DB_CCCD_COUNT != 0u) */
    .gattDB = cy_ble_gattDB,
    #endif /* CY_BLE_GATT_ROLE_SERVER */

    /** Initialize the device security structure */
    #if(CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL)
    .authInfo = cy_ble_authInfo,
    #endif /* (CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL */

    /** Initialize the BLE configuration parameters structure */
    .params = &cy_ble_params,

    /** Bluetooth Device Address */
    .deviceAddress = &cy_ble_deviceAddress,

    #if(CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL)
    /** Services initialize function */
    .ServiceInitFunc = &Cy_BLE_ServiceInit,
    #endif /* (CY_BLE_GAP_ROLE_CENTRAL || CY_BLE_GAP_ROLE_PERIPHERAL */

    /** Internal structures */
    #if (CY_BLE_GATT_ROLE_SERVER || CY_BLE_GATT_ROLE_CLIENT)
    .context = &cy_ble_contex,
    #endif /* (CY_BLE_GATT_ROLE_SERVER || CY_BLE_GATT_ROLE_CLIENT) */
#endif /* (CY_BLE_MODE_PROFILE) */

    /** BLE stack configuration */
    .stackParam = &stackParam,

    /** BLE HW configuration */
    .hw = &cy_ble_hwConfig,
};


/*******************************************************************************
 *  SERVICE SPECIFIC CONFIGURATIONS
 *******************************************************************************/

#if (CY_BLE_MODE_PROFILE)

/**
 * GAP
 **/
#if (CY_BLE_GATT_ROLE_SERVER)
    /* Structure for store discovered attributes information */
    const cy_stc_ble_gaps_t cy_ble_gaps =
    {
        0x0001u, /* Handle of the GAP service */ 
        0x0003u, /* Handle of the Device Name characteristic */ 
        0x0005u, /* Handle of the Appearance characteristic */ 
        CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Peripheral Preferred Connection Parameters characteristic */ 
        CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Central Address Resolution characteristic */ 
        CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Resolvable Private Address Only characteristic */
    };

    /* The configuration structure for the GAP (client) */
    const cy_stc_ble_gaps_config_t cy_ble_gapsConfig =
    {
        .attrInfo = (cy_stc_ble_gaps_t *)&cy_ble_gaps,
    };
#endif /*(CY_BLE_GATT_ROLE_SERVER) */

#if (CY_BLE_GATT_ROLE_CLIENT)
    /* Structure for store discovered attributes information */
    cy_stc_ble_gapc_t cy_ble_gapc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the GATT (client) */
    const cy_stc_ble_gapc_config_t cy_ble_gapcConfig =
    {
        .attrInfo = cy_ble_gapc,
        .serviceDiscIdx = CY_BLE_SRVI_GAP,
    };
#endif /*(CY_BLE_GATT_ROLE_CLIENT) */


/**
 * GATT
 **/
#if (CY_BLE_GATT_ROLE_SERVER)
    /* Service GATT DB handles structure */
    const cy_stc_ble_gatts_t cy_ble_gatts =
    {
        0x0006u, /* Handle of the GATT service */ 
        CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Service Changed characteristic */ 
        CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Client Characteristic Configuration descriptor */
    };

    /* The configuration structure for the GATT (client) */
    const cy_stc_ble_gatts_config_t cy_ble_gattsConfig =
    {
        .attrInfo  = (cy_stc_ble_gatts_t *)&cy_ble_gatts,
    };
#endif /*(CY_BLE_GATT_ROLE_SERVER) */

#if (CY_BLE_GATT_ROLE_CLIENT)
    /* Structure for store discovered attributes information */
    cy_stc_ble_gattc_t cy_ble_gattc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the GATT (client) */
    const cy_stc_ble_gattc_config_t cy_ble_gattcConfig =
    {
        .attrInfo = cy_ble_gattc,
        .serviceDiscIdx = CY_BLE_SRVI_GATT,
    };
#endif /* CY_BLE_GATT_ROLE_CLIENT */


/**
 * ANCS
 **/
#ifdef CY_BLE_ANCS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_ancss_t cy_ble_ancss =
    {
       
    };

    /* The configuration structure for the Apple Notification Center service (server). */
    const cy_stc_ble_ancss_config_t cy_ble_ancssConfig =
    {
        .attrInfo = &cy_ble_ancss,
    };
#endif /* CY_BLE_ANCS_SERVER */

#ifdef CY_BLE_ANCS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_ancsc_t cy_ble_ancsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Apple Notification Center service (client). */
    const cy_stc_ble_ancsc_config_t cy_ble_ancscConfig =
    {
        .attrInfo       = cy_ble_ancsc,
        .serviceDiscIdx = CY_BLE_SRVI_ANCS,
    };
#endif /* CY_BLE_ANCS_CLIENT */


/**
 * ANS
 **/
#ifdef CY_BLE_ANS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_anss_t cy_ble_anss =
    {
       
    };

    /* The configuration structure for the Alert Notification service (server). */
    const cy_stc_ble_anss_config_t cy_ble_anssConfig =
    {
        .attrInfo = &cy_ble_anss,
    };
#endif /* CY_BLE_ANS_SERVER */

#ifdef CY_BLE_ANS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_ansc_t cy_ble_ansc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Alert Notification service (client). */
    const cy_stc_ble_ansc_config_t cy_ble_anscConfig =
    {
        .attrInfo       = cy_ble_ansc,
        .serviceDiscIdx = CY_BLE_SRVI_ANS,
    };
#endif /* CY_BLE_ANS_CLIENT */


/**
 * AIOS
 **/
#ifdef CY_BLE_AIOS_SERVER

    /* Digital characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_aioss_char_t aiossCharIdx0[0x00u] =
    {
        
    };
    #endif /* Count of Digital characteristics != 0 */

    
    /* Analog characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_aioss_char_t aiossCharIdx1[0x00u] =
    {
        
    };
    #endif /* Count of Analog characteristics != 0 */


    /* Aggregate characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_aioss_char_t aiossCharIdx2[0x00u] =
    {
        
    };
    #endif /* Count of Aggregate characteristics != 0 */

    /* Number of AIOS characteristics instances */
    static const uint8_t cy_ble_aiossCharInstances[CY_BLE_CONFIG_AIOS_CHAR_INST_COUNT] =
    {
        
    };

    /* Service GATT DB handles structure */
    const cy_stc_ble_aioss_t cy_ble_aioss =
    {
       
    };

    /* The configuration structure for the Automation Input Output service (server). */
    const cy_stc_ble_aioss_config_t cy_ble_aiossConfig =
    {
        .attrInfo = &cy_ble_aioss,
        .charInstances  = cy_ble_aiossCharInstances,
    };
#endif /* CY_BLE_AIOS_SERVER */

#ifdef CY_BLE_AIOS_CLIENT
    /* Digital characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_aiosc_char_t aioscCharIdx0[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Digital characteristics != 0 */

    /* Analog characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_aiosc_char_t aioscCharIdx1[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Analog characteristics != 0 */

    /* Aggregate characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_aiosc_char_t aioscCharIdx2[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Aggregate characteristics != 0 */
    
    /* Number of AIOS characteristics instances */
    static const uint8_t cy_ble_aioscCharInstances[CY_BLE_CONFIG_AIOS_CHAR_INST_COUNT] =
    {
        
    };
    /* Structure for store discovered attributes information */
    const cy_stc_ble_aiosc_t cy_ble_aiosc[CY_BLE_GATTC_COUNT] =
    {
        
    };

    /* The configuration structure for the Automation Input Output service (client). */
    const cy_stc_ble_aiosc_config_t cy_ble_aioscConfig =
    {
        .attrInfo       = cy_ble_aiosc,
        .charInstances  = cy_ble_aioscCharInstances,
        .serviceDiscIdx = CY_BLE_SRVI_AIOS,
    };
#endif /* CY_BLE_AIOS_CLIENT */


/**
 * BAS
 **/
#ifdef CY_BLE_BAS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_bass_t cy_ble_bass[CY_BLE_CONFIG_BASS_SERVICE_COUNT] =
    {
        /* Battery */
        {
            0x0007u, /* Handle of the BAS service */ 
            0x0009u, /* Handle of the Battery Level characteristic */ 
            0x000Au, /* Handle of the Characteristic Presentation Format descriptor */ 
            0x000Bu, /* Handle of the Client Characteristic Configuration descriptor */ 
        },
    };

    /* The configuration structure for the Battery Service (server) */
    const cy_stc_ble_bass_config_t cy_ble_bassConfig =
    {
        .attrInfo     = cy_ble_bass,
        .serviceCount = CY_BLE_CONFIG_BASS_SERVICE_COUNT,
    };
#endif /* CY_BLE_BAS_SERVER */

#ifdef CY_BLE_BAS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_basc_t cy_ble_basc[CY_BLE_GATTC_COUNT]
                                 [CY_BLE_CONFIG_BASC_SERVICE_COUNT];

    /* The configuration structure for the Battery Service (client) */
    const cy_stc_ble_basc_config_t cy_ble_bascConfig =
    {
        .attrInfo       = (cy_stc_ble_basc_t *)cy_ble_basc,
        .serviceCount   = CY_BLE_CONFIG_BASC_SERVICE_COUNT,
        .serviceDiscIdx = CY_BLE_SRVI_BAS,
    };
#endif /* CY_BLE_BAS_CLIENT */


/**
 * BLS
 **/
#ifdef CY_BLE_BLS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_blss_t cy_ble_blss =
    {
       
    };

    /* The configuration structure for the Blood Pressure service (server). */
    const cy_stc_ble_blss_config_t cy_ble_blssConfig =
    {
        .attrInfo = &cy_ble_blss,
    };
#endif /* CY_BLE_BLS_SERVER */

#ifdef CY_BLE_BLS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_blsc_t cy_ble_blsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Blood Pressure service (client). */
    const cy_stc_ble_blsc_config_t cy_ble_blscConfig =
    {
        .attrInfo       = cy_ble_blsc,
        .serviceDiscIdx = CY_BLE_SRVI_BLS,
    };
#endif /* CY_BLE_BLS_CLIENT */


/**
 * BCS
 **/
#ifdef CY_BLE_BCS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_bcss_t cy_ble_bcss =
    {
       
    };

    /* The configuration structure for the Body Composition service (server). */
    const cy_stc_ble_bcss_config_t cy_ble_bcssConfig =
    {
        .attrInfo = &cy_ble_bcss,
    };
#endif /* CY_BLE_BCS_SERVER */

#ifdef CY_BLE_BCS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_bcsc_t cy_ble_bcsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Body Composition service (client). */
    const cy_stc_ble_bcsc_config_t cy_ble_bcscConfig =
    {
        .attrInfo       = cy_ble_bcsc,
        .serviceDiscIdx = CY_BLE_SRVI_BCS,
    };
#endif /* CY_BLE_BCS_CLIENT */


/**
 * BMS
 **/
#ifdef CY_BLE_BMS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_bmss_t cy_ble_bmss =
    {
       
    };

    /* The configuration structure for the Bond Management service (server). */
    const cy_stc_ble_bmss_config_t cy_ble_bmssConfig =
    {
        .attrInfo = &cy_ble_bmss,
    };
#endif /* CY_BLE_BMS_SERVER */

#ifdef CY_BLE_BMS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_bmsc_t cy_ble_bmsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Bond Management service (client). */
    const cy_stc_ble_bmsc_config_t cy_ble_bmscConfig =
    {
        .attrInfo       = cy_ble_bmsc,
        .serviceDiscIdx = CY_BLE_SRVI_BMS,
    };
#endif /* CY_BLE_BMS_CLIENT */


/**
 * BTS
 **/
#ifdef CY_BLE_BTS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_btss_t cy_ble_btss =
    {
       
    };

    /* The configuration structure for the Bootloader service (server). */
    const cy_stc_ble_btss_config_t cy_ble_btssConfig =
    {
        .attrInfo = &cy_ble_btss,
    };
#endif /* CY_BLE_BTS_SERVER */


/**
 * CGMS
 **/
#ifdef CY_BLE_CGMS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_cgmss_t cy_ble_cgmss =
    {
       
    };

    /* The configuration structure for the Continuous Glucose Monitoring service (server). */
    const cy_stc_ble_cgmss_config_t cy_ble_cgmssConfig =
    {
        .attrInfo = &cy_ble_cgmss,
    };
#endif /* CY_BLE_CGMS_SERVER */

#ifdef CY_BLE_CGMS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_cgmsc_t cy_ble_cgmsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Continuous Glucose Monitoring service (client). */
    const cy_stc_ble_cgmsc_config_t cy_ble_cgmscConfig =
    {
        .attrInfo       = cy_ble_cgmsc,
        .serviceDiscIdx = CY_BLE_SRVI_CGMS,
    };
#endif /* CY_BLE_CGMS_CLIENT */


/**
 * CPS
 **/
#ifdef CY_BLE_CPS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_cpss_t cy_ble_cpss =
    {
       
    };

    /* The configuration structure for the Cycling Power Service service (server). */
    const cy_stc_ble_cpss_config_t cy_ble_cpssConfig =
    {
        .attrInfo = &cy_ble_cpss,
    };
#endif /* CY_BLE_CPS_SERVER */

#ifdef CY_BLE_CPS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_cpsc_t cy_ble_cpsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Cycling Power Service service (client). */
    const cy_stc_ble_cpsc_config_t cy_ble_cpscConfig =
    {
        .attrInfo       = cy_ble_cpsc,
        .serviceDiscIdx = CY_BLE_SRVI_CPS,
    };
#endif /* CY_BLE_CPS_CLIENT */


/**
 * CSCS
 **/
#ifdef CY_BLE_CSCS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_cscss_t cy_ble_cscss =
    {
       
    };

    /* The configuration structure for the Cycling Speed and Cadence service (server). */
    const cy_stc_ble_cscss_config_t cy_ble_cscssConfig =
    {
        .attrInfo = &cy_ble_cscss,
    };
#endif /* CY_BLE_CSCS_SERVER */

#ifdef CY_BLE_CSCS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_cscsc_t cy_ble_cscsc[CY_BLE_GATTC_COUNT];

    /* Flash storage for discovered attributes information */
    CY_SECTION(".cy_em_eeprom") CY_ALIGN(CY_FLASH_SIZEOF_ROW)
    static const cy_stc_ble_cscsc_t cy_ble_flashCscsc[CY_BLE_GATTC_COUNT] =
    {
        {
            .characteristics[CY_BLE_CSCS_CSC_MEASUREMENT] =
            {
                .charInfo    = { 0u, 0u                 },
                .endHandle   = 0u,
                .descriptors = { 0u }
            },
            .characteristics[CY_BLE_CSCS_CSC_FEATURE] =
            {
                .charInfo    = { 0u, 0u                 },
                .endHandle   = 0u,
                .descriptors = { 0u }
            },
            .characteristics[CY_BLE_CSCS_SENSOR_LOCATION] =
            {
                .charInfo    = { 0u, 0u                 },
                .endHandle   = 0u,
                .descriptors = { 0u }
            },
            .characteristics[CY_BLE_CSCS_SC_CONTROL_POINT] =
            {
                .charInfo    = { 0u, 0u                 },
                .endHandle   = 0u,
                .descriptors = { 0u }
            },
        }
    };

    /* The configuration structure for the Cycling Speed and Cadence service (client). */
    const cy_stc_ble_cscsc_config_t cy_ble_cscscConfig =
    {
        .attrInfo       = cy_ble_cscsc,
        .flashAtrInfo   = cy_ble_flashCscsc,
        .serviceDiscIdx = CY_BLE_SRVI_CSCS,
    };
#endif /* CY_BLE_CSCS_CLIENT */


/**
 * CTS
 **/
#ifdef CY_BLE_CTS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_ctss_t cy_ble_ctss =
    {
       
    };

    /* The configuration structure for the Current Time service (server). */
    const cy_stc_ble_ctss_config_t cy_ble_ctssConfig =
    {
        .attrInfo = &cy_ble_ctss,
    };
#endif /* CY_BLE_CTS_SERVER */

#ifdef CY_BLE_CTS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_ctsc_t cy_ble_ctsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Current Time service (client). */
    const cy_stc_ble_ctsc_config_t cy_ble_ctscConfig =
    {
        .attrInfo       = cy_ble_ctsc,
        .serviceDiscIdx = CY_BLE_SRVI_CTS,
    };
#endif /* CY_BLE_CTS_CLIENT */


/**
 * CUSTOM
 **/
#ifdef CY_BLE_CUSTOM_SERVER
    /* This array contains attribute handles for the defined descriptors
     * of Custom services.
     * The array index definitions are located in the cy_cfg.h file. */
    #if (CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_DESCRIPTORS_COUNT != 0u) 
    const cy_ble_gatt_db_attr_handle_t cy_ble_customSDesc[CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_DESCRIPTORS_COUNT] =
    {
        
    };
    #endif /* (CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_DESCRIPTORS_COUNT != 0u) */
    
    /* This array contains attribute handles for the defined characteristics
     * of Custom services.
     * The array index definitions are located in the cy_cfg.h file. */
    #if (CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_COUNT != 0u) 
    const cy_stc_ble_customs_info_t cy_ble_customSChar[CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_COUNT] =
    {
        
    };
    #endif /* (CY_BLE_CONFIG_CUSTOMS_SERVICE_CHAR_COUNT != 0u) */

    /* This array contains attribute handle and pointer to characteristic
    * information array for the defined of Custom services.
    * The array index definitions are located in the cy_cfg.h file. */
    const cy_stc_ble_customs_t cy_ble_customSServ[CY_BLE_CONFIG_CUSTOMS_SERVICE_COUNT] =
    {
        
    };

    /** The configuration structure for the Custom services (server). */
    const cy_stc_ble_customs_config_t cy_ble_customsConfig =
    {
        .attrInfo = cy_ble_customSServ,
    };
#endif /* CY_BLE_CUSTOM_SERVER */

#ifdef CY_BLE_CUSTOM_CLIENT
    static uint16_t cy_ble_customCServHandle[CY_BLE_CONFIG_CUSTOMC_SERVICE_COUNT][CY_BLE_GATTC_COUNT] = {CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE};

    #if (CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT != 0u)
    static uint16_t cy_ble_customCCharHandle[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT][CY_BLE_GATTC_COUNT] = {CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE};
    static uint16_t cy_ble_customCCharEndHandle[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT][CY_BLE_GATTC_COUNT] = {CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE};
    static uint8 cy_ble_customCCharProperties[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT][CY_BLE_GATTC_COUNT] = {CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE};
    #endif /* (CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT != 0u) */

    #if (CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_DESCRIPTORS_COUNT != 0u)
    static uint16_t cy_ble_customCDescHandle[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_DESCRIPTORS_COUNT][CY_BLE_GATTC_COUNT]  = {CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE};
    #endif /* (CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_DESCRIPTORS_COUNT != 0u) */

    #if (CY_BLE_CONFIG_CUSTOMC_UUID_128_COUNT != 0u)
    static const cy_stc_ble_uuid128_t cy_ble_customCUuid128[CY_BLE_CONFIG_CUSTOMC_UUID_128_COUNT] =
    {
        
    };
    #endif /* (CY_BLE_CONFIG_CUSTOMC_UUID_128_COUNT != 0u) */

    #if (CY_BLE_CONFIG_CUSTOMC_UUID_16_COUNT != 0u)
    static const uint16_t cy_ble_customCUuid16[CY_BLE_CONFIG_CUSTOMC_UUID_16_COUNT] =
    {
        
    };
    #endif /* (CY_BLE_CONFIG_CUSTOMC_UUID_16_COUNT != 0u) */

    static const cy_stc_ble_customc_desc_t cy_ble_customCDesc[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_DESCRIPTORS_COUNT] =
    {
        
    };
    static const cy_stc_ble_customc_char_t cy_ble_customCChar[CY_BLE_CONFIG_CUSTOMC_SERVICE_CHAR_COUNT] =
    {
        
    };
    const cy_stc_ble_customc_t cy_ble_customCServ[CY_BLE_CONFIG_CUSTOMC_SERVICE_COUNT] =
    {
        
    };

    /** The configuration structure for the Custom services (client). */
    const cy_stc_ble_customc_config_t cy_ble_customcConfig =
    {
        .attrInfo = cy_ble_customCServ,
        .serviceCount = CY_BLE_CONFIG_CUSTOMC_SERVICE_COUNT,
        .serviceDiscIdx = CY_BLE_SRVI_CUSTOMS,
    };
#endif /* CY_BLE_CUSTOM_CLIENT */


/**
 * DIS
 **/
#ifdef CY_BLE_DIS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_diss_t cy_ble_diss =
    {
        .serviceHandle = 0x000Cu, /* Handle of the DIS service */ 
        .charHandle = {
            0x000Eu, /* Handle of the Manufacturer Name String characteristic */ 
            0x0010u, /* Handle of the Model Number String characteristic */ 
            CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Serial Number String characteristic */ 
            0x0012u, /* Handle of the Hardware Revision String characteristic */ 
            0x0014u, /* Handle of the Firmware Revision String characteristic */ 
            CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the Software Revision String characteristic */ 
            CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the System ID characteristic */ 
            CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the IEEE 11073-20601 Regulatory Certification Data List characteristic */ 
            CY_BLE_GATT_INVALID_ATTR_HANDLE_VALUE, /* Handle of the PnP ID characteristic */ 
        },
    };

    /* The configuration structure for the Device Information service (server) */
    const cy_stc_ble_diss_config_t cy_ble_dissConfig =
    {
        .attrInfo = &cy_ble_diss,
    };
#endif /* CY_BLE_DIS_SERVER */

#ifdef CY_BLE_DIS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_disc_t cy_ble_disc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Device Information service  (client) */
    const cy_stc_ble_disc_config_t cy_ble_discConfig =
    {
        .attrInfo       = cy_ble_disc,
        .serviceDiscIdx = CY_BLE_SRVI_DIS,
    };
#endif /* CY_BLE_DIS_CLIENT */


/**
 * ESS
 **/
#ifdef CY_BLE_ESS_SERVER

    /* Descriptor Value Changed characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx0[0x00u] =
    {
        
    };
    #endif /* Count of Descriptor Value Changed characteristic data != 0 */

    /* Apparent Wind Direction characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx1[0x00u] =
    {
        
    };
    #endif /* Count of Apparent Wind Direction characteristic data != 0 */

    /* Apparent Wind Speed characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx2[0x00u] =
    {
        
    };
    #endif /* Count of Apparent Wind Speed characteristic data != 0 */

    /* Dew Point characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx3[0x00u] =
    {
        
    };
    #endif /* Count of Dew Point characteristic data != 0 */

    /* Elevation characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx4[0x00u] =
    {
        
    };
    #endif /* Count of Elevation characteristic data != 0 */

    /* Gust Factor characteristic data */
    #if (0x00u != 0x00u)   
    static const cy_stc_ble_esss_char_t esssCharIdx5[0x00u] =
    {
        
    };
    #endif /* Count of Gust Factor characteristic data != 0 */

    /* Heat Index characteristic data */
    #if (0x00u != 0x00u)    
    static const cy_stc_ble_esss_char_t esssCharIdx6[0x00u] =
    {
        
    };
    #endif /* Count of Heat Index characteristic data != 0 */
    
    /* Humidity characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx7[0x00u] =
    {
        
    };
    #endif /* Count of Humidity characteristic data != 0 */

    /* Irradiance characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx8[0x00u] =
    {
        
    };
    #endif /* Count of Irradiance characteristic data != 0 */

    /* Pollen Concentration characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx9[0x00u] =
    {
        
    };
    #endif /* Count of Pollen Concentration characteristic data != 0 */

    /* Rainfall characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx10[0x00u] =
    {
        
    };
    #endif /* Count of Rainfall characteristic data != 0 */

    /* Pressure characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx11[0x00u] =
    {
         
    };
    #endif /* Count of Pressure characteristic data != 0 */

    /* Temperature characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx12[0x00u] =
    {
         
    };
    #endif /* Count of Temperature characteristic data != 0 */

    /* True Wind Direction characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx13[0x00u] =
    {
         
    };
    #endif /* Count of True Wind Direction characteristic data != 0 */

    /* True Wind Speed characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx14[0x00u] =
    {
         
    };
    #endif /* Count of True Wind Speed characteristic data != 0 */

    /* UV Index characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx15[0x00u] =
    {
         
    };
    #endif /* Count of UV Index characteristic data != 0 */

    /* Wind Chill characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx16[0x00u] =
    {
         
    };
    #endif /* Count of Wind Chill characteristic data != 0 */

    /* Barometric Pressure Trend characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx17[0x00u] =
    {
         
    };
    #endif /* Count of Barometric Pressure Trend characteristic data != 0 */

    /* Magnetic Declination characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx18[0x00u] =
    {
         
    };
    #endif /* Count of Magnetic Declination characteristic data != 0 */

    /* Magnetic Flux Density - 2D characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx19[0x00u] =
    {
         
    };
    #endif /* Count of Magnetic Flux Density - 2D characteristic data != 0 */

    /* Magnetic Flux Density - 3D characteristic data */
    #if (0x00u != 0x00u)
    static const cy_stc_ble_esss_char_t esssCharIdx20[0x00u] =
    {
         
    };
    #endif /* Count of Magnetic Flux Density - 3D characteristic data != 0 */
    
    /* Number of ESS characteristics instances */
    static const uint8_t cy_ble_esssCharInstances[CY_BLE_CONFIG_ESS_CHAR_INST_COUNT] =
    {
         
    };

    const cy_stc_ble_esss_t cy_ble_esss =
    {
        
    };

    /* The configuration structure for the Environmental Sensing service (server). */
    const cy_stc_ble_esss_config_t cy_ble_esssConfig =
    {
        .attrInfo = &cy_ble_esss,
        .charInstances  = cy_ble_esssCharInstances,
    };

#endif /* CY_BLE_ESS_SERVER */

#ifdef CY_BLE_ESS_CLIENT
    /* Descriptor Value Changed characteristic data */
    #if (0x00u != 0x00u)  
    static cy_stc_ble_essc_char_t esscCharIdx0[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Descriptor Value Changed characteristic data != 0 */

    /* Apparent Wind Direction characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx1[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Apparent Wind Direction characteristic data != 0 */

    /* Apparent Wind Speed characteristic data */
    #if (0x00u != 0x00u)  
    static cy_stc_ble_essc_char_t esscCharIdx2[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Apparent Wind Speed characteristic data != 0 */

    /* Dew Point characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx3[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Dew Point characteristic data != 0 */

    /* Elevation characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx4[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Elevation characteristic data != 0 */

    /* Gust Factor characteristic data */
    #if (0x00u != 0x00u)       
    static cy_stc_ble_essc_char_t esscCharIdx5[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Gust Factor characteristic data != 0 */

    /* Heat Index characteristic data */
    #if (0x00u != 0x00u)       
    static cy_stc_ble_essc_char_t esscCharIdx6[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Heat Index characteristic data != 0 */

    /* Humidity characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx7[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Humidity characteristic data != 0 */

    /* Irradiance characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx8[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Irradiance characteristic data != 0 */

    /* Pollen Concentration characteristic data */
    #if (0x00u != 0x00u)   
    static cy_stc_ble_essc_char_t esscCharIdx9[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Pollen Concentration characteristic data != 0 */
 
    /* Rainfall characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx10[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Rainfall characteristic data != 0 */

    /* Pressure characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx11[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Pressure characteristic data != 0 */

    /* Temperature characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx12[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Temperature characteristic data != 0 */

    /* True Wind Direction characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx13[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of True Wind Direction characteristic data != 0 */

    /* True Wind Speed characteristic data */
    #if (0x00u != 0x00u)    
    static cy_stc_ble_essc_char_t esscCharIdx14[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of True Wind Speed characteristic data != 0 */

    /* UV Index characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx15[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of UV Index characteristic data != 0 */

    /* Wind Chill characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx16[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Wind Chill characteristic data != 0 */

    /* Barometric Pressure Trend characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx17[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Barometric Pressure Trend characteristic data != 0 */

    /* Magnetic Declination characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx18[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Magnetic Declination characteristic data != 0 */

    /* Magnetic Flux Density - 2D characteristic data */
    #if (0x00u != 0x00u)   
    static cy_stc_ble_essc_char_t esscCharIdx19[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Magnetic Flux Density - 2D characteristic data != 0 */

    /* Magnetic Flux Density - 3D characteristic data */
    #if (0x00u != 0x00u)
    static cy_stc_ble_essc_char_t esscCharIdx20[CY_BLE_GATTC_COUNT][0x00u];
    #endif /* Count of Magnetic Flux Density - 3D characteristic data != 0 */

    /* Number of ESS characteristics instances */
    static const uint8_t cy_ble_esscCharInstances[CY_BLE_CONFIG_ESS_CHAR_INST_COUNT] = {
        
    };

    /* Structure for store discovered attributes information */
    const cy_stc_ble_essc_t cy_ble_essc[CY_BLE_GATTC_COUNT] =
    {
        
    };

    /* The configuration structure for the Environmental Sensing service (client). */
    const cy_stc_ble_essc_config_t cy_ble_esscConfig =
    {
        .attrInfo       = cy_ble_essc,
        .charInstances  = cy_ble_esscCharInstances,
        .serviceDiscIdx = CY_BLE_SRVI_ESS,
    };
#endif /* CY_BLE_ESS_CLIENT */


/**
 * GLS
 **/
#ifdef CY_BLE_GLS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_glss_t cy_ble_glss =
    {
       
    };

    /* The configuration structure for the Glucose service (server). */
    const cy_stc_ble_glss_config_t cy_ble_glssConfig =
    {
        .attrInfo = &cy_ble_glss,
    };
#endif /* CY_BLE_GLS_SERVER */

#ifdef CY_BLE_GLS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_glsc_t cy_ble_glsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Glucose service (client). */
    const cy_stc_ble_glsc_config_t cy_ble_glscConfig =
    {
        .attrInfo       = cy_ble_glsc,
        .serviceDiscIdx = CY_BLE_SRVI_GLS,
    };
#endif /* CY_BLE_GLS_CLIENT */


/**
 * HIDS
 **/
#ifdef CY_BLE_HIDS_SERVER
    /* Service GATT DB handles structures */
    /* HID Server Report characteristic */
    static const cy_stc_ble_hidss_report_t cy_ble_hidssReportArray[CY_BLE_CONFIG_HIDSS_REPORT_COUNT] =
    {
        
    };

    /* HID Service attribute handles */
    const cy_stc_ble_hidss_t cy_ble_hidss[CY_BLE_CONFIG_HIDSS_SERVICE_COUNT] =
    {
        
    };

    /* The configuration structure for the HID service (server) */
    const cy_stc_ble_hidss_config_t cy_ble_hidssConfig =
    {
        .attrInfo     = cy_ble_hidss,
        .serviceCount = CY_BLE_CONFIG_HIDSS_SERVICE_COUNT,
        .reportCount  = CY_BLE_CONFIG_HIDSC_REPORT_COUNT,
    };
#endif /* CY_BLE_HIDS_SERVER */

#ifdef CY_BLE_HIDS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_hidsc_t cy_ble_hidsc[CY_BLE_GATTC_COUNT]
                                   [CY_BLE_CONFIG_HIDSC_SERVICE_COUNT];

    /** The configuration structure for the HID service (client) */
    const cy_stc_ble_hidsc_config_t cy_ble_hidscConfig =
    {
        .attrInfo       = (cy_stc_ble_hidsc_t *)cy_ble_hidsc,
        .serviceCount   = CY_BLE_CONFIG_HIDSC_SERVICE_COUNT,
        .reportCount    = CY_BLE_CONFIG_HIDSC_REPORT_COUNT,
        .serviceDiscIdx = CY_BLE_SRVI_HIDS,
    };
#endif /* CY_BLE_HIDS_CLIENT */

/**
 * HPS
 **/
#ifdef CY_BLE_HPS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_hpss_t cy_ble_hpss =
    {
       
    };

    /* The configuration structure for the HTTP Proxy service (server). */
    const cy_stc_ble_hpss_config_t cy_ble_hpssConfig =
    {
        .attrInfo = &cy_ble_hpss,
    };
#endif /* CY_BLE_HPS_SERVER */

#ifdef CY_BLE_HPS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_hpsc_t cy_ble_hpsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the HTTP Proxy service (client). */
    const cy_stc_ble_hpsc_config_t cy_ble_hpscConfig =
    {
        .attrInfo       = cy_ble_hpsc,
        .serviceDiscIdx = CY_BLE_SRVI_HPS,
    };
#endif /* CY_BLE_HPS_CLIENT */


/**
 * HRS
 **/
#ifdef CY_BLE_HRS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_hrss_t cy_ble_hrss =
    {
       
    };

    /* The configuration structure for the Heart Rate service (server). */
    const cy_stc_ble_hrss_config_t cy_ble_hrssConfig =
    {
        .attrInfo = &cy_ble_hrss,
    };
#endif /* CY_BLE_HRS_SERVER */

#ifdef CY_BLE_HRS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_hrsc_t cy_ble_hrsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Heart Rate service (client). */
    const cy_stc_ble_hrsc_config_t cy_ble_hrscConfig =
    {
        .attrInfo       = cy_ble_hrsc,
        .serviceDiscIdx = CY_BLE_SRVI_HRS,
    };
#endif /* CY_BLE_HRS_CLIENT */


/**
 * HTS
 **/
#ifdef CY_BLE_HTS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_htss_t cy_ble_htss =
    {
        
    };

    /* The configuration structure for the Health Thermometer service (server) */
    const cy_stc_ble_htss_config_t cy_ble_htssConfig =
    {
        .attrInfo = &cy_ble_htss,
    };
#endif /* CY_BLE_HTS_SERVER */

#ifdef CY_BLE_HTS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_htsc_t cy_ble_htsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Health Thermometer service (client) */
    const cy_stc_ble_htsc_config_t cy_ble_htscConfig =
    {
        .attrInfo       = cy_ble_htsc,
        .serviceDiscIdx = CY_BLE_SRVI_HTS,
    };
#endif /* CY_BLE_HTS_CLIENT */


/**
 * IAS
 **/
#ifdef CY_BLE_IAS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_iass_t cy_ble_iass =
    {
        
    };

    /* The configuration structure for the Immediate Alert service (server) */
    const cy_stc_ble_iass_config_t cy_ble_iassConfig =
    {
        .attrInfo = &cy_ble_iass,
    };
#endif /* CY_BLE_IAS_SERVER */

#ifdef CY_BLE_IAS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_iasc_t cy_ble_iasc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Immediate Alert service (client) */
    const cy_stc_ble_iasc_config_t cy_ble_iascConfig =
    {
        .attrInfo       = cy_ble_iasc,
        .serviceDiscIdx = CY_BLE_SRVI_IAS,
    };
#endif /* CY_BLE_IAS_CLIENT */


/**
 * IPS
 **/
#ifdef CY_BLE_IPS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_ipss_t cy_ble_ipss =
    {
       
    };

    /* The configuration structure for the Indoor Positioning service (server). */
    const cy_stc_ble_ipss_config_t cy_ble_ipssConfig =
    {
        .attrInfo = &cy_ble_ipss,
    };
#endif /* CY_BLE_IPS_SERVER */

#ifdef CY_BLE_IPS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_ipsc_t cy_ble_ipsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Indoor Positioning service (client). */
    const cy_stc_ble_ipsc_config_t cy_ble_ipscConfig =
    {
        .attrInfo       = cy_ble_ipsc,
        .serviceDiscIdx = CY_BLE_SRVI_IPS,
    };
#endif /* CY_BLE_IPS_CLIENT */


/**
 * LLS
 **/
#ifdef CY_BLE_LLS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_llss_t cy_ble_llss =
    {
        
    };

    /* The configuration structure for the Link Loss service (server) */
    const cy_stc_ble_llss_config_t cy_ble_llssConfig =
    {
        .attrInfo = &cy_ble_llss,
    };
#endif /* CY_BLE_LLS_SERVER */

#ifdef CY_BLE_LLS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_llsc_t cy_ble_llsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Link Loss service (client) */
    const cy_stc_ble_llsc_config_t cy_ble_llscConfig =
    {
        .attrInfo       = cy_ble_llsc,
        .serviceDiscIdx = CY_BLE_SRVI_LLS,
    };
#endif /* CY_BLE_LLS_CLIENT */


/**
 * LNS
 **/
#ifdef CY_BLE_LNS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_lnss_t cy_ble_lnss =
    {
       
    };

    /* The configuration structure for the Location and Navigation service (server). */
    const cy_stc_ble_lnss_config_t cy_ble_lnssConfig =
    {
        .attrInfo = &cy_ble_lnss,
    };
#endif /* CY_BLE_LNS_SERVER */

#ifdef CY_BLE_LNS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_lnsc_t cy_ble_lnsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Location and Navigation service (client). */
    const cy_stc_ble_lnsc_config_t cy_ble_lnscConfig =
    {
        .attrInfo       = cy_ble_lnsc,
        .serviceDiscIdx = CY_BLE_SRVI_LNS,
    };
#endif /* CY_BLE_LNS_CLIENT */


/**
 * NDCS
 **/
#ifdef CY_BLE_NDCS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_ndcss_t cy_ble_ndcss =
    {
       
    };

    /* The configuration structure for the Next DST Change service (server). */
    const cy_stc_ble_ndcss_config_t cy_ble_ndcssConfig =
    {
        .attrInfo = &cy_ble_ndcss,
    };
#endif /* CY_BLE_NDCS_SERVER */

#ifdef CY_BLE_NDCS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_ndcsc_t cy_ble_ndcsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Next DST Change service (client). */
    const cy_stc_ble_ndcsc_config_t cy_ble_ndcscConfig =
    {
        .attrInfo       = cy_ble_ndcsc,
        .serviceDiscIdx = CY_BLE_SRVI_NDCS,
    };
#endif /* CY_BLE_NDCS_CLIENT */


/**
 * PASS
 **/
#ifdef CY_BLE_PASS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_passs_t cy_ble_passs =
    {
       
    };

    /* The configuration structure for the Phone Alert Status service (server). */
    const cy_stc_ble_passs_config_t cy_ble_passsConfig =
    {
        .attrInfo = &cy_ble_passs,
    };
#endif /* CY_BLE_PASS_SERVER */

#ifdef CY_BLE_PASS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_passc_t cy_ble_passc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Phone Alert Status service (client). */
    const cy_stc_ble_passc_config_t cy_ble_passcConfig =
    {
        .attrInfo       = cy_ble_passc,
        .serviceDiscIdx = CY_BLE_SRVI_PASS,
    };
#endif /* CY_BLE_PASS_CLIENT */

/**
 * PLXS
 **/
#ifdef CY_BLE_PLXS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_plxss_t cy_ble_plxss =
    {
       
    };

    /* The configuration structure for the Pulse Oximeter service (server). */
    const cy_stc_ble_plxss_config_t cy_ble_plxssConfig =
    {
        .attrInfo = &cy_ble_plxss,
    };
#endif /* CY_BLE_PLXS_SERVER */

#ifdef CY_BLE_PLXS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_plxsc_t cy_ble_plxsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Pulse Oximeter service (client). */
    const cy_stc_ble_plxsc_config_t cy_ble_plxscConfig =
    {
        .attrInfo       = cy_ble_plxsc,
        .serviceDiscIdx = CY_BLE_SRVI_PLXS,
    };
#endif /* CY_BLE_PLXS_CLIENT */


/**
 * RSCS
 **/
#ifdef CY_BLE_RSCS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_rscss_t cy_ble_rscss =
    {
       
    };

    /* The configuration structure for the Running Speed and Cadence service (server). */
    const cy_stc_ble_rscss_config_t cy_ble_rscssConfig =
    {
        .attrInfo = &cy_ble_rscss,
    };
#endif /* CY_BLE_RSCS_SERVER */

#ifdef CY_BLE_RSCS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_rscsc_t cy_ble_rscsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Running Speed and Cadence service (client). */
    const cy_stc_ble_rscsc_config_t cy_ble_rscscConfig =
    {
        .attrInfo       = cy_ble_rscsc,
        .serviceDiscIdx = CY_BLE_SRVI_RSCS,
    };
#endif /* CY_BLE_RSCS_CLIENT */


/**
 * RTUS
 **/
#ifdef CY_BLE_RTUS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_rtuss_t cy_ble_rtuss =
    {
       
    };

    /* The configuration structure for the Reference Time Update service (server). */
    const cy_stc_ble_rtuss_config_t cy_ble_rtussConfig =
    {
        .attrInfo = &cy_ble_rtuss,
    };
#endif /* CY_BLE_RTUS_SERVER */

#ifdef CY_BLE_RTUS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_rtusc_t cy_ble_rtusc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Reference Time Update service (client). */
    const cy_stc_ble_rtusc_config_t cy_ble_rtuscConfig =
    {
        .attrInfo       = cy_ble_rtusc,
        .serviceDiscIdx = CY_BLE_SRVI_RTUS,
    };
#endif /* CY_BLE_RTUS_CLIENT */


/**
 * SCPS
 **/
#ifdef CY_BLE_SCPS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_scpss_t cy_ble_scpss =
    {
        
    };

    /* The configuration structure for the Scan Parameter service (server) */
    const cy_stc_ble_scpss_config_t cy_ble_scpssConfig =
    {
        .attrInfo = &cy_ble_scpss,
    };
#endif /* CY_BLE_SCPS_SERVER */

#ifdef CY_BLE_SCPS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_scpsc_t cy_ble_scpsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Scan Parameter service (client) */
    const cy_stc_ble_scpsc_config_t cy_ble_scpscConfig =
    {
        .attrInfo       = cy_ble_scpsc,
        .serviceDiscIdx = CY_BLE_SRVI_SCPS,
    };
#endif /* CY_BLE_SCPS_CLIENT */


/**
 * TPS
 **/
#ifdef CY_BLE_TPS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_tpss_t cy_ble_tpss =
    {
        
    };

    /* The configuration structure for the Tx Power service (server) */
    const cy_stc_ble_tpss_config_t cy_ble_tpssConfig =
    {
        .attrInfo = &cy_ble_tpss,
    };
#endif /* CY_BLE_TPS_SERVER */

#ifdef CY_BLE_TPS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_tpsc_t cy_ble_tpsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Tx Power service (client) */
    const cy_stc_ble_tpsc_config_t cy_ble_tpscConfig =
    {
        .attrInfo       = cy_ble_tpsc,
        .serviceDiscIdx = CY_BLE_SRVI_TPS,
    };
#endif /* CY_BLE_TPS_CLIENT */


/**
 * WSS
 **/
#ifdef CY_BLE_WSS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_wsss_t cy_ble_wsss =
    {
        
    };

    /* The configuration structure for the Weight Scale service (server). */
    const cy_stc_ble_wsss_config_t cy_ble_wsssConfig =
    {
        .attrInfo = &cy_ble_wsss,
    };
#endif /* CY_BLE_WSS_SERVER */

#ifdef CY_BLE_WSS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_wssc_t cy_ble_wssc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Weight Scale service (client). */
    const cy_stc_ble_wssc_config_t cy_ble_wsscConfig =
    {
        .attrInfo       = cy_ble_wssc,
        .serviceDiscIdx = CY_BLE_SRVI_WSS,
    };
#endif /* CY_BLE_WSS_CLIENT */


/**
 * UDS
 **/
#ifdef CY_BLE_UDS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_udss_t cy_ble_udss =
    {
        
    };

    /* The configuration structure for the User Data service (server). */
    const cy_stc_ble_udss_config_t cy_ble_udssConfig =
    {
        .attrInfo = &cy_ble_udss,
    };
#endif /* CY_BLE_UDS_SERVER */

#ifdef CY_BLE_UDS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_udsc_t cy_ble_udsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the User Data service (client). */
    const cy_stc_ble_udsc_config_t cy_ble_udscConfig =
    {
        .attrInfo       = cy_ble_udsc,
        .serviceDiscIdx = CY_BLE_SRVI_UDS,
    };
#endif /* CY_BLE_UDS_CLIENT */

/**
 * WPTS
 **/
#ifdef CY_BLE_WPTS_SERVER
    /* Service GATT DB handles structure */
    const cy_stc_ble_wptss_t cy_ble_wptss =
    {
        
    };

    /* The configuration structure for the Wireless Power Transfer service (server). */
    const cy_stc_ble_wptss_config_t cy_ble_wptssConfig =
    {
        .attrInfo = &cy_ble_wptss,
    };
#endif /* CY_BLE_WPTS_SERVER */

#ifdef CY_BLE_WPTS_CLIENT
    /* Structure for store discovered attributes information */
    cy_stc_ble_wptsc_t cy_ble_wptsc[CY_BLE_GATTC_COUNT];

    /* The configuration structure for the Wireless Power Transfer service (client). */
    const cy_stc_ble_wptsc_config_t cy_ble_wptscConfig =
    {
        .attrInfo       = cy_ble_wptsc,
        .serviceDiscIdx = CY_BLE_SRVI_WPTS,
    };
#endif /* CY_BLE_WPTS_CLIENT */

#endif /* (CY_BLE_MODE_PROFILE) */
#endif /* (CY_BLE_CORE == CY_BLE_CORE_DUAL) || (CY_BLE_CORE == __CORTEX_M) */

/* [] END OF FILE */

