/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.44.                           *
*        Compiled Nov 10 2017, 08:51:52                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: CypressLogo_1bpp                         *
* Dimensions:  260 * 80                                              *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmCypressLogo_1bpp;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsCypressLogo_1bpp[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalCypressLogo_1bpp = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsCypressLogo_1bpp[0]
};

static GUI_CONST_STORAGE unsigned char _acCypressLogo_1bpp[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXX__, ________, ________, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXX__, ________, ________, _XXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXX___, ________, ________, _XXXXXXX, XXXXXX__, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXX___, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ____XXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXX_, _____XXX, XXXXX___, ___XXXX_, ________, _____XXX, XXXXXXXX, ________, _____XXX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXX_, ________, XXXXXX__, __XX____,
  XXXX____, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, _____XXX, XXXXXXXX, XXXX____, ________, _XXXXXX_, ______XX, XXXXX___, ___XXXX_, ________, _______X, XXXXXXXX, ________, _______X, XXXXXXXX, X_______, ________, ____XXXX, XXXX____, ________, XXXXXXXX, XXXXX___, ________, _XXXX_X_, __XX____,
  XXXX____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________, __XXXXXX, ______XX, XXXX____, ___XXXX_, ________, ________, XXXXXXXX, ________, ________, _XXXXXXX, X_______, ________, ____XXXX, XXX_____, ________, __XXXXXX, XXXX____, ________, __XXX_X_, _XXX____,
  XXX_____, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________, ______XX, XXXXXXXX, XX______, ________, ___XXXXX, _______X, XXXX____, __XXXXX_, ________, ________, _XXXXXXX, ________, ________, __XXXXXX, X_______, ________, ____XXXX, XX______, ________, ___XXXXX, XXX_____, ________, ___XXX__, __XX____,
  XXX_____, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XX______, ________, ___XXXXX, _______X, XXXX____, __XXXXX_, ________, ________, __XXXXXX, ________, ________, __XXXXXX, X_______, ________, ____XXXX, X_______, ________, ___XXXXX, XX______, ________, ____XXXX, XXXX____,
  XX______, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, X_______, ________, ____XXXX, X______X, XXX_____, __XXXXX_, ________, ________, __XXXXXX, ________, ________, ___XXXXX, X_______, ________, ____XXXX, X_______, ________, ____XXXX, XX______, ________, ____XXXX, XXXX____,
  XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXX___, ____XXXX, X_______, XXX_____, _XXXXXX_, _____XXX, XXX_____, ___XXXXX, ______XX, XXXX____, ___XXXXX, X______X, XXXXXXXX, XXXXXXXX, X_______, XXXXX___, ____XXXX, X_______, XXXXXX__, _____XXX, XXXX____,
  XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, XXXXXX__, ____XXXX, X_______, XXX_____, _XXXXXX_, _____XXX, XXXX____, ___XXXXX, ______XX, XXXXX___, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X_______, XXXXXX__, _____XXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XX______, XX______, _XXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XX______, XX______, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXX_____, _X______, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXX_____, _______X, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X_______, XXXXXXX_, _____XXX, XXXX____,
  X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXX_____, _______X, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, X_______, XXXXXXX_, ____XXXX, X_______, XXXXXXX_, _____XXX, XXXX____,
  ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXX____, _______X, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXX____,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ______XX, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXX____,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ______XX, XXXXXXX_, _____XXX, XXXXX___, ___XXXXX, ______XX, XXXXX___, ____XXXX, X______X, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXX____,
  ________, ________, ___XXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, _XXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXX_, _____XXX, XXXX____, ___XXXXX, ______XX, XXXX____, ___XXXXX, X_______, ________, _XXXXXXX, XXX_____, ____XXXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXX____,
  ________, ________, ___XXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, _XXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXX_, _____XXX, XXX_____, ___XXXXX, ________, ________, ___XXXXX, X_______, ________, _XXXXXXX, XXXX____, _____XXX, XXXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXX____,
  ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXX_, ________, ________, __XXXXXX, ________, ________, __XXXXXX, X_______, ________, _XXXXXXX, XXXXX___, ______XX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXX____,
  ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXXXXX_, ________, ________, __XXXXXX, ________, ________, __XXXXXX, X_______, ________, _XXXXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXX____,
  ________, ________, ________, ________, ________, _XXXX___, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, ________, ________, _XXXXXXX, ________, ________, _XXXXXXX, X_______, ________, _XXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXX____,
  ________, ________, ________, ________, ________, __XXXX__, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, ________, ________, XXXXXXXX, ________, ________, XXXXXXXX, X_______, ________, _XXXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, X_______, __XXXXXX, XXXX____,
  ________, ________, ________, ________, ________, ___XXXX_, _____XXX, XXX_____, ________, ________, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, ________, _______X, XXXXXXXX, ________, ________, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XX______, ___XXXXX, XXXX____,
  ________, ________, ________, ________, ________, ____XXXX, ____XXXX, XX______, ________, ________, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, ________, ____XXXX, XXXXXXXX, ______XX, XX______, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXX____,
  ________, ________, ________, ________, ________, _____XXX, X___XXXX, X_______, ________, ________, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XX______, XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXX____,
  X_______, ________, ________, ________, ________, _____XXX, XX_XXXXX, ________, ________, ________, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XX______, _XXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ____XXXX, XXXXXXXX, XXXXXX__, _____XXX, XXXX____,
  X_______, ________, ________, ________, ________, ______XX, XXXXXXXX, ________, ________, ________, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXX_____, _XXXXXXX, X______X, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXX__, _____XXX, XXXX____,
  X_______, ________, ________, ________, ________, _______X, XXXXXXX_, ________, ________, ________, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXX_____, _XXXXXXX, X______X, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  X_______, ________, ________, ________, ________, ______XX, XXXXXX__, ________, ________, ________, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXX_____, _XXXXXXX, X______X, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  X_______, ________, ________, ________, ________, _____XXX, XXXXX___, ________, ________, _______X, XXXXXXXX, _______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXX____, __XXXXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X______X, XXXXXXX_, _____XXX, XXXX____,
  XX______, ________, ________, ________, ________, _____XXX, XXXXX___, ________, ________, _______X, XXXXXXXX, X______X, XXXXXX__, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXX____, __XXXXXX, X______X, XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, ____XXXX, X_______, XXXXXX__, _____XXX, XXXX____,
  XX______, ________, ________, ________, ________, ____XXXX, XXXX____, ________, ________, _______X, XXXXXXXX, X_______, XXXXX___, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXX____, __XXXXXX, X______X, XXXXXXXX, XXXXXXXX, X_______, XXXXX___, ____XXXX, X_______, _XXXXX__, _____XXX, XXXX____,
  XX______, ________, ________, ________, ________, ___XXXXX, XX______, ________, ________, ______XX, XXXXXXXX, X_______, ________, ____XXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXX____, ___XXXXX, X_______, ________, ____XXXX, X_______, ________, ____XXXX, XX______, ________, ____XXXX, XXXX____,
  XXX_____, ________, ________, ________, ________, __XXXXXX, X_______, ________, ________, ______XX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, X_______, ________, ____XXXX, X_______, ________, ___XXXXX, XX______, ________, ____XXXX, XXXX____,
  XXX_____, ________, ________, ________, ________, __XXXXXX, ________, ________, ________, ______XX, XXXXXXXX, XX______, ________, ___XXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, X_______, ________, ____XXXX, XX______, ________, __XXXXXX, XXX_____, ________, ___XXXXX, XXXX____,
  XXXX____, ________, ________, ________, ________, _XXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXX_____, ________, __XXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXX___, ___XXXXX, X_______, ________, ____XXXX, XXX_____, ________, __XXXXXX, XXXX____, ________, __XXXXXX, XXXX____,
  XXXX____, ________, ________, ________, ________, XXXXXXX_, ________, ________, ________, _____XXX, XXXXXXXX, XXXX____, ________, _XXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXX___, ____XXXX, X_______, ________, ____XXXX, XXXX____, ________, XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXX____,
  XXXXX___, ________, ________, ________, _______X, XXXXXX__, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXX__, ____XXXX, X_______, ________, ____XXXX, XXXXXX__, _______X, XXXXXXXX, XXXXXXX_, _______X, XXXXXXXX, XXXX____,
  XXXXX___, ________, ________, ________, _______X, XXXXX___, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXX__, ________, ________, ________, ______XX, XXXX____, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXX__, ________, ________, ________, _____XXX, XXXX____, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, X_______, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, X__XXXX_, _XXX____, _XXX____, ___XX___, __XXXX__, ___XXX__, ____XX__, ____XXXX, XXX__XX_, _XXX__XX, XXXX____, __XXX___, _XXXX__X, XXX__XXX, _____XXX, ______XX, X______X, XXX____X, XX__XX__, XX__XXX_, X_X_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, X___XXX_, _XXX____, __XX____, __XXX___, ___XXX__, ____XX__, ____XX__, _____XXX, XXX__XX_, __XX__XX, XXXX____, __XX___X, __XXX__X, XX___XX_, __X___XX, _______X, X______X, XX__X___, XX__XX__, XX__XXX_, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XXXXX, X___XX__, _XXX__XX, __XX__XX, XXXXX_XX, X__XXX_X, XX__XX__, XXXXXX__, XXX__XXX, XXX__XX_, ___X__XX, XXXXXX__, XXXX__XX, __XXX___, XX___XX_, _XXX__XX, __XXX__X, X__XXX__, X__XXX__, XX__X___, _X__XXXX, XXXX____,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, X_____XX, X____X__, _XXX____, __XX____, _XXXX_XX, X__XXX_X, XX__XX__, ___XXX__, XXX__XXX, XXX__XX_, ___X__XX, XXXXXX__, XXXX__XX, X_XXX___, X____XX_, _XXX__XX, __XX___X, X__XX__X, X__XXX__, XX__X___, _X__XXXX, XXXX____,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, X_____XX, X_______, _XXX____, __XX____, __XXX_XX, X__XXX_X, XX__XX__, ____XX__, XXX__XXX, XXX__XX_, _X____XX, XXXXXX__, XXXX__XX, X_XXX___, _____XX_, _XXX__XX, ______XX, X______X, X__XXX__, XXX_____, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, X__XXXXX, X__X____, _XXX__XX, __XX__XX, XXXXX_XX, X__XXX_X, XX__XX__, XXXXXX__, XXX__XXX, XXX__XX_, _X____XX, XXXXXX__, XXXX__XX, X_XXX___, __X__XX_, _XXX__XX, __X__XXX, X__X__XX, X__XXX__, XXX___XX, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, X__XXXXX, X__X__X_, _XXX__XX, __XX__XX, XXXXX_XX, X__XXX_X, XX__XX__, XXXXXX__, XXX__XXX, XXX__XX_, _XX___XX, XXXXXX__, XXXX__XX, __XXX__X, __X__XX_, _XXX__XX, __XX__XX, X__XX__X, XX__XX__, XXX___XX, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, X__XXXX_, _XXX____, __XX____, __XXX___, ___XXX__, ____XX__, ____XX__, _____XXX, XXX__XX_, _XXX__XX, XXXXXX__, XXXX____, __XXX__X, XXX__XXX, _____XXX, __XX__XX, X__XX__X, XX______, XXX___XX, ___XXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, X__XXXX_, _XXX____, _XXXX___, __XXX___, __XXXX__, __XXXX__, ____XXX_, ___XXXXX, XXX__XX_, _XXX__XX, XXXXXX__, XXXXX___, _XXXX_XX, XXX__XXX, X___XXXX, __XXX__X, X__XXX__, XXX____X, XXXX_XXX, X_XXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____
};

GUI_CONST_STORAGE GUI_BITMAP bmCypressLogo_1bpp = {
  260, // xSize
  80, // ySize
  33, // BytesPerLine
  1, // BitsPerPixel
  _acCypressLogo_1bpp,  // Pointer to picture data (indices)
  &_PalCypressLogo_1bpp   // Pointer to palette
};

/*************************** End of file ****************************/
